### ISSUE TITLE
`npm run build` fails with babel error

### ISSUE THREAD

**Issue by radio-alice** [Webstrates/Webstrates#108]
`npm run build` fails with the following error (both on my machine and on a replit dev server)

```
ERROR in ./client/index.js
Module build failed: Error: [BABEL] Webstrates/client/index.js: Could not find plugin "proposal-numeric-separator".
```

I don't know much about babel but based on a quick search "proposal-numeric-separator" isn't mentioned in y'all's configs so best guess is that upgrading some module broke it.

[link to repl where you can see for yourself](https://repl.it/@zachsherman/webstrates)
Lmk if there's anything else I can do to help debug/fix.

**Comment by radio-alice** [comment]
after playing with the more looks like the build starts failing after [this commit](https://github.com/Webstrates/Webstrates/commit/b6c484fde81eb6fe62884ee16a31139337e21e67)

**Comment by radio-alice** [comment]
fixed and [PRed](https://github.com/Webstrates/Webstrates/pull/109)!

**Comment by kbadk** [comment]
Thanks for the contribution! Stay safe.
