### ISSUE TITLE
Deleting a webstrate with ?delete does not clear tags from shareBD

### ISSUE THREAD

**Issue by dkgof** [Webstrates/Webstrates#114]
If you create a webstrate, add some tags. Then delete the webstrate, and recreate it with the same name. All the old tags are still there.

**Comment by kbadk** [comment]
The issue appears to have been introduced [in this commmit from last year](https://github.com/Webstrates/Webstrates/commit/4327e6d1c9c199cabb5933fec19868eed52c061f#diff-c9e8a1719b333d0e6cb55a9ea0d3d08d8e909197ed290b1bb1dc3d72e7387919R265). `remove` was replaced with `removeOne` in a few instances where multiple docuemnts were deleted before. It also appears this would cause ops to be left behind as well. `removeOne` should probably be replaced with [`deleteMany`](https://docs.mongodb.com/drivers/node/current/fundamentals/crud/write-operations/delete/) in those instances.

**Comment by dkgof** [comment]
That would be when i updated mongodb client to the latest version, without understanding mongodb as it was my first encounter.

I guess ill go over it again.
