### ISSUE TITLE
Missing tutorial and first try on Windows crashes

### ISSUE THREAD

**Issue by MikaelMayer** [Webstrates/Webstrates#13]
Dear developers,

There is a link the word `tutorial` on the README.md

> See the tutorial for an introduction to developing with Webstrates.

but this link is broken. Can you please fix it? I could not find it anywhere.

**Comment by kbadk** [comment]
I can see you have already fixed this yourself. Thank you! Could you create a new issue detailing the crash you're experiencing on Windows?

**Comment by MikaelMayer** [comment]
Which crash? Are you talking about this [issue](https://github.com/Webstrates/Webstrates/issues/14)?

**Comment by kbadk** [comment]
No, this issue was previously named "Missing tutorial and first try on Windows crashes".

**Comment by MikaelMayer** [comment]
Oh sorry I saw that I was putting the crash on Windows in the title, but in the meanwhile I solved it. It was because I needed to launch MangoDB, which was written nowhere (I did not have an experience doing so, I figured out after looking 20 minutes why it was not working)
Basically, I just needed to go to `Program Files/MongoDB/Server/3.4/bin` and launch `./mongod.exe`
