### ISSUE TITLE
Webstrates sync bug.

### ISSUE THREAD

**Issue by MikaelMayer** [Webstrates/Webstrates#14]
To reproduce this bug, do the following:

* Navigate to `http://localhost:7007/grip/`
* Open another tab in which you navigate also to `http://localhost:7007/grip/`
* Replace the body in the first tab with "edit as html" (in Chrome) to:
```html
<body contenteditable="true">
  This is an interesting test
  <br>
</body>
```
* Then left-click on the sentence "This is an interesting test" and again "edit as html". Edit the sentence by adding bold markers around `interesting`:
```html
This is an <b>interesting</b> test
```

* Observe the result in the two viewers. First viewer:

```html
<body contenteditable="true">
This is an <b>interesting</b> test
  <br>
</body>
```

Second viewer:
```html
<body contenteditable="true"> test
  <b>interesting</b>
This is an <br>
</body>
```

Note that in order to edit the text as HTML, you need a second node, that is why I added a <br> originally. Also, the elements are still synchronized, but they keep the reverse order.

Hope this helps.
Best regards,

**Comment by kbadk** [comment]
On which version (or commit) are you experiencing this? This was (hopefully) resolved Jan 19, 2017. Could you try using the most recent commit?

**Comment by MikaelMayer** [comment]
I did the tests on the following revision:

Revision: 3098c45aa80b09d4b8dee2fe2be7e65cf2278bfc
Author: Kristian Antonsen <kba@cs.au.dk>
Date: 28/01/2017 18:42:49
Message:
Fixed bug causing own clientId to occur twice in webstrate.clients.

**Comment by kbadk** [comment]
Have you upgraded from an older version and perhaps relying on the browser's cache of the older version, or forgotten to do `npm run build-babel` after upgrading? I haven't been able to reproduce when following your steps on several installations.

Could you try with a clean installation, possibly in Incognito mode to ensure there are no lingering caches?

Also, thank you for taking som time to help improve Webstrates!

**Comment by MikaelMayer** [comment]
With a new fresh version, I cannot reproduce the problem.
However, with the previous version, I can still reproduce the problem.

Do you think it may be because MongoDB was not running at the time I ran `npm run build-babel` ?

**Comment by kbadk** [comment]
It's not likely to have anything to do with MongoDB. My bet is the browser used the cached version of `static/webstrates.createops.js`. Anyway, I'm glad you solved it!

**Comment by MikaelMayer** [comment]
If it were the case, after right-clicking on the refresh arrow, "empty cache and force refresh" on both sides should solve the problem. But even with that, the problem in the previous version is still the same.

I used WinMerge to see what the difference was between the `webstrates.createops.js` on the two installations, and I see this difference:
Line 196, it is

    while (previousSibling && previousSibling.webstrate) {
			
on the faulty installation, whereas on the correct one it is

    while (previousSibling && previousSibling.tagName && previousSibling.tagName.toLowerCase() === "transient")

Later, we have:

    (mutation.target.webstrate || newPathNode.parent.DOMNode.webstrate).fireEvent("nodeAdded", addedNode, true);

which has been updated to:

    mutation.target.webstrate.fireEvent("nodeAdded", addedNode, true);

and same for nodeRemoved.

How does it come since the only difference between these two checkouts is my commit, which does not touch this file?

**Comment by kbadk** [comment]
Hard to say. Those changes are definitely unrelated to this bug.

**Comment by MikaelMayer** [comment]
That's even weirder. This commit: 057fc2646cd13bc02101529eff2e8a325eedfd61 is in the faulty installation, but not in the newest checked out one. I bet that you rebased and reverted it?

**Comment by MikaelMayer** [comment]
ok let me change some files until I cannot reproduce the bug in my previous installation, I'll tell you what fixed it.

**Comment by kbadk** [comment]
Ah, yes, it could definitely be a rebase. The particular line that causes the bug is:

    var previousSibling = addedNode.previousSibling;

which should be:

    var previousSibling = mutation.previousSibling;

in `static/webstrates.createops.js`. 

But I wouldn't waste anymore time on it if I was you. As long as the newest version works, everything is good.

**Comment by MikaelMayer** [comment]
After I replaced the old version of `webstrates.createops.js` to the new one, I was not able to reproduce this bug anymore. Not even if I went back to the old version either. So from now that's good I won't waste anymore time. Thanks for the explanation.
