### ISSUE TITLE
vsce can crash the server

### ISSUE THREAD

**Issue by svnhub** [Webstrates/Webstrates#18]
When you exit the editor it can somehow crash the server with the following trace:
`helpers/ClientManager.js:234

clients[socketId].[^]webstrates[webstrateId].foreach(function(nodeId){

TypeError: Cannot read property 'webstrates' of undefined

   at Object.module.removeClientFromWebstrate (helpers/ClientManager.js:234:21)

....
`

**Comment by kbadk** [comment]
Do you know if this is still possible?

**Comment by svnhub** [comment]
Haven't seen this or #24 in a while

**Comment by kbadk** [comment]
Thought so, I do think I fixed it at some point, but forgot to close the issues. Thanks.
