### ISSUE TITLE
Feature request: md5sum on assets

### ISSUE THREAD

**Issue by svnhub** [Webstrates/Webstrates#19]
It would be really nice to somehow be able to check the md5 of uploaded assets attached to a webstrate without having to download them and perform the check locally. It could either be included in the list of assets in ?assets requests or some kind of specific request for that one asset. The same could be the case for the returned json when uploading the asset initially.

A small optimization of the current asset system could be to also re-use the existing asset file in the new asset version when md5 is the same (or not create a new version) - to save on disk space on the server.

**Comment by kbadk** [comment]
I agree and this is on the TODO list. :-)
