### ISSUE TITLE
Feature request: Transient data attributes

### ISSUE THREAD

**Issue by svnhub** [Webstrates/Webstrates#21]
Suggestion for adding support for transient attributes that work just like the existing transient tag - for instance everything that starts with "data-transient-...".

This is useful for storing extra temporary info and state related to specific DOM-elements without causing updates to that attribute to propagate to the server and other users.
Since data attributes are target-able from CSS it can also be used to control local changes to the view that will be lost upon update of the page (for instance selecting files from a list, visibility of popup menus, etc.) without having to move the entire structure into a <transient> tag when loading the webstrate.

**Comment by kbadk** [comment]
This was implemented a while ago, see [the documentation on Transient](https://webstrates.github.io/userguide/api/transient.html#transient-attributes).
