### ISSUE TITLE
file-system script can crash the server

### ISSUE THREAD

**Issue by svnhub** [Webstrates/Webstrates#24]
This is probably related to #18 but gets its own issue since the situation is a bit different:
When using the file-system monitoring script and stopping it with ctrl+c sometimes the Webstrates server that the script was connected to will crash with the following stack-trace:
```
node_modules/mogodb/lib/utils.js:98
process.nextTick(function(){ throw err;});

TypeError: Cannot read property 'webstrates' of undefined
at Object.module.removeClientFromWebstrate (ClientManager.js:234:21)
at webstrates.js:333:22
at PermissionManager.js:66:4
...
at node_modules/sharedb/lib/backend.js:286:13
at node_modules/sharedb-mongo/index.js:254:7
at handleCallback (node_modules/mongodb/lib/utils.js:95:56)
at node_modules/mongodb/lib/cursor.js:674:5
```

**Comment by kbadk** [comment]
This was fixed at some point that I can't remember. Closing. See #18.
