### ISSUE TITLE
Transient attributes on added elements

### ISSUE THREAD

**Issue by svnhub** [Webstrates/Webstrates#28]
Newly added DOM elements with transient attributes have their transient attributes sent via webstrates even though they have been marked as transient. Further updates to the transient attribute after the element was initially created are not transferred.

Try this code in two tabs:
```
<html><head><title>transient-create-testcase</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script>
    function addThing(){
  jQuery("body").append("<test transient-class='ost'></test>");
    }
</script></head><body>

  <button onclick="addThing()">
Click ME
</button></body></html>
```

Also available at https://hikaru.cs.au.dk/transient-create-testcase/

Expected behaviour: The element is created but transient information is not communicated via webstrates.

**Comment by kbadk** [comment]
Good catch, I never considered that when implementing it. I've fixed it in the devel branch (which will merge with the master branch soon-ish).
