### ISSUE TITLE
Performance suggestion: maxAge cache parameters

### ISSUE THREAD

**Issue by svnhub** [Webstrates/Webstrates#30]
At the moment Webstrates serves static content with a cache max-age of 0, meaning that browsers have to perform a If-Modified-Since request for the resources on every load of a webstrate. Since webstrate.js and the webstrate favicon usually do not change on every request the normal response is 304 Not Modified but the latency to the server and back can be fairly high if a lot of other requests are also queued up because a lot of webstrates are loaded simultaneously.

Changing to:
`app.use(express.static("static", {maxAge:"1d"}));`
allows browsers to perform client-side caching instead, avoiding the round-trip time entirely by serving directly from memory.

Note: Opening developer's console usually disables caching entirely, remember the "Disable cache" setting/checkbox.

Effect: In a cached test case with a webstrate containing 10 sub-webstrates webstrates.js load time was reduced from around 180ms to 0.1ms and number of hits on the server was reduced from 11 to 0.

**Comment by svnhub** [comment]
Similarly for the client.html served to bootstrap webstrates.js in helpers/HttpRequestController.js, changing to:
`return res.sendFile(APP_PATH + "/static/client.html", {maxAge:"1d"});`
will avoid roundtrip delays for webstrates that have already been visited - and since the bootstrapper content is always the same anyways there is no need to perform a request just to get the 304 Not Modified response.

**Comment by kbadk** [comment]
Good idea, thanks! Now implemented in [`084c34d`](https://github.com/Webstrates/Webstrates/commit/084c34d1f3adb0b2ee7040d0fa83397d2454a649).

Note that [Chrome sends `Cache-Control: max-age=0` on new requests](https://superuser.com/questions/313131/how-do-i-stop-chrome-sending-cache-control-max-age-0-when-i-hit-enter) though, so the `client.html` often won't get cached anyway. It should add a good speed-up to `webstrates.js` though (currently 368 KB).
