### ISSUE TITLE
Connect event never triggers, disconnect event triggers twice and repeatedly

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#35]
Adding a `connect` event listener to the webstrate object (`webstrate.on("connect")`) works, but the event never triggers. 

The `disconnect` event gets triggered twice on a client disconnect, and it triggers repeatedly; it triggers twice every time the client tries to reconnect to the server. It should be enough to trigger the `disconnect` event only once. Maybe a `webstrate.connectionState` object that holds this information could be useful.

The `reconnect` event works as expected.

A minimal example can be found here: https://webstrates.cs.au.dk/disconnect-reconnect/ 
Open the webstrate and wait until it has loaded (the word `Log` should be visible in the page). Then disconnect and wait till events get triggered.

**Comment by kbadk** [comment]
Thanks, I've removed the `connect` event and fixed the `reconnect` event, so it only triggers once "per connect", i.e. it doesn't trigger repeatedly when getting disconnected while attempting to reconnect.
