### ISSUE TITLE
Turn on/off attribute value diffing on client-side

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#36]
It would be great to have the option to turn off (and on) attribute value diffing on client-side. The default should be configuration should `on`.

At the moment, we are maintaining two different servers with almost identical codebases. The only difference is that attribute value diffing is turned off on `hikaru`. With a configurable attribute value diffing we could return to previous Webstrates deployment/staging process where webstrates.cs.au.dk is the stable deployment and hikaru.cs.au.dk becomes the devel deployment again. It's also easier to maintain research prototypes running on either Webstrates or Codestrates.

Suggestions for the client API are:

```
webstrate.attributeValueDiffing = false;
```

or

```
webstrate.config.attributeValueDiffing = false;
```

or a more general approach includes one of the two options:

```
webstrate.set("attributeValueDiffing", false);
```

or

```
webstrate.setConfig("attributeValueDiffing", false);
```

Thanks!

**Comment by kbadk** [comment]
As of right now, the frontend consists of a core modules and optional modules. Particularly, the webstrate object in userland is an optional module whereas the the module responsible for generating ops is mandatory. As such, if we make a mandatory module depend on an optional module, that module is no longer optional. maybe we should do away with the distinction, but I guess that's a discussion for another day.

Either way, I've now added this to a mandatory client config module (`coreConfig`), which `coreOpCreator` then depends on. The optional module `globalObject` is now allowed to edit this module. We'll therefore be going with your second approach: `webstrate.config.attributeValueDiffing`. Keep in mind that this value has to be reset whenever the browser gets reloaded.

**Comment by raedle** [comment]
Great! Thank you
