### ISSUE TITLE
Deleting a message does not update webstrate.messages on other clients

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#37]
Deleting a message via `webstrate.deleteMessage` updates the `webstrate.messages` array, but other clients connected with the same user still have all messages including the deleted messages.

A minimal example is here: https://webstrates.cs.au.dk/Hkrl-O8oW/?copy

Steps to reproduce:

1. Open the example in two browser tabs
2. The example logs `webstrate.messages.length` every 10 seconds
3. Click on the `create dummy message` button to create dummy messages if you have 0 messages!
4. Watch both browser tabs log the same message count.
5. Click on the `delete last message` button to delete the last message from the messages array! The two browser tabs now log different numbers for message count.
6. A page reload updates to the correct message count

**Comment by kbadk** [comment]
This has been fixed in 9a34793.

**Comment by raedle** [comment]
It works! Thanks
