### ISSUE TITLE
How to add transcluded event listener to iframes originating from a template?

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#40]
I have a webstrate with a `<template>` element and the template contains an `iframe` element.

```
<template id="iframe-template">
  <iframe src="/frame-testA/"></iframe>
</template>
```

I import the template with `document.importNode`, then query the `iframe`, and add a `transcluded` event listener to the iframe. But, elements do not have a `webstrate` object after the `importNode` function call and the `webstrate` object does not exist after appending the fragment to the document. But, a `webstrate` object exists for the template, the template's `DocumentFragment`, and all of its decedents.

Here is an example: https://webstrates.cs.au.dk/template-webstrate-object/

The `Add iFrame` buttons creates an `iframe` element through `document.createElement` and the resulting element has a `webstrate` object.

The `Add iFrame from template` creates an `iframe` element through a `template` and the resulting element has no `webstrate` object.

What's the best way to use `template` to create elements and then being able to add a `transcluded` event to `iframe` elements that were generated from the template?

**Comment by kbadk** [comment]
Good catch! We've already implemented overrides on `document.createElement`, `document.createElementNS` and `Element.cloneNode` that will create a `webstrate` object when the element is created. `document.importNode` had been forgotten, but it has now been implemented here as well. There may still be more methods of creating elements that we've forgotten, so if you encounter a similar problem with another method of element creation, it's most likely a bug, too.

I've adapted the implementation to now also work with `document.importNode`. A quick workaround if a similar issue should occur in the future: The `webstrate` object is always to an element after it has been inserted into the DOM (assuming it doesn't have one). So even without this fix, you can just wait a tick and add it (i.e. add the event listener in a `setTimeout`, so you give time for the MutationObserver to do its job).
