### ISSUE TITLE
Carry over query parameters when copying a webstrate

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#46]
When using the `?copy` parameter, additional query parameters are discarded after the browser was redirected to the copy.

For example, `https://demo.webstrates.net/frontpage/?copy&foo=bar` will redirect to <COPY_OF_FRONTPAGE>, but the `foo` parameter is not carried over `https://demo.webstrates.net/<COPY_OF_FRONTPAGE>/?foo=bar`.

However, sometimes it is very useful to define query parameters for just copied webstrate, e.g. to define what content is shown or hidden on the first load.

**Comment by raedle** [comment]
Cosmetics, but using `https://webstrates.cs.au.dk/loud-rat-9/?copy&edit` will turn into `https://webstrates.cs.au.dk/white-rabbit-44/?edit=` (spot the equal sign `=`).

Avoid `=` and value for query parameters that have `undefined` values. Otherwise, a JS function that returns the url parameters cannot distinguish between `undefined` and `""` (empty string) values

**Comment by kbadk** [comment]
This is how [the native Node.js `url` module](https://nodejs.org/api/url.html) does it:

```
> require('url').format({ pathname: '/path', query: { foo: 'bar', quux: undefined } });
'/path?foo=bar&quux='
```

The query string does not carry types. Just as you don't know whether `2` in `foo=2` is meant to be a number of a string, we also don't know whether `?copy=` (or `copy`) is meant to be interpreted as `undefined` or an empty stirng. This information is simply not available, so trying to extract it by creating your own interpretation will be very fragile.

The information is not available. Don't try to infer it. I trust Node.js' URL module. This is a no fix, sorry.
