### ISSUE TITLE
Allow to define subpath when uploading assets

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#47]
Assets are addressed by a webstrate id and their filename (e.g., [https://webstrates.cs.au.dk/fat-rat-83/codemirror.js](https://webstrates.cs.au.dk/fat-rat-83/codemirror.js)). However, CodeMirror names addons like `comment.js` or `dialog.js` and puts them into sub subfolders within a codemirror folder; thereby grouping the addons and make them eventually distinguishable from third-party libraries having the same naming conventions for their JavaScript files.

It would be nice to have the option to define arbitrary subpaths between the webstrate id and the filename (e.g. [https://webstrates.cs.au.dk/fat-rat-83/codemirror/addon/comment/comment.js](https://webstrates.cs.au.dk/fat-rat-83/codemirror/addon/comment/comment.js)).

This will also make it easier in future to replace entire libraries just by uploading the `dist` folder instead of tediously renaming each file every time a new version is uploaded.

I'm aware that it conflicts with the `version` and `tag` functionality of Webstrates, but you guys are smart and possibly figure out how it can be implemented ;)

**Comment by kbadk** [comment]
This will interfere with tags. Is  `baz.ext` in `/foo/bar/baz.ext` from tag `bar`or from the head with subdirectory `bar`? Even if we did work around this issue (blacklist the creating of tags used as folders and vice versa), it's sure to cause confusion in the long run.

I suggest you just name your assets like `codemrror-addon-comment-comment.js` instead. No major libraries (to the best of my knowledge) depend on the relative paths of each component.

I think implementing this will cause more harm than good as a result of the URL ambiguity when the only benefit I see from it is that `/codemirror/addon/comment/comment.js` is slightly more conventional than `/codemrror-addon-comment-comment.js`.

**Comment by raedle** [comment]
I'll reopen this issue because an external library—I'd like to use—requires support for subpaths to import other external files on page load via a `loader.js` (the external library is [monaco-editor](https://github.com/Microsoft/monaco-editor)). Unfortunately, access to change the `loader.js` behavior is very limited (at least I haven't found a way to change its behavior).

Would it work to prepend the subpath `assets` when referring to an asset? For example, `cow.jpg` will be accessible via `/myWebstrate/assets/cow.jpg` and within a webstrate it would be `<img src="assets/cow.jpg">`. Thereby, tags could still work as before (except for the now used `assets` path, which is similar to the `auth` path (i.e. `/auth/github`)). Then, assets in tag `myTag` would be `/myWebstrate/myTag/assets/cow.jpg` and version `7` would be `/myWebstrate/7/assets/cow.jpg` and `<img src="myTag/assets/cow.jpg">` respectively.
