### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by svnhub** [Webstrates/Webstrates#49]
When working with webstrates and assets across multiple webstrate servers it would be beneficial to have CORS header support for accessing the various webstrate and asset mechanisms, for example raw/jsonml export and asset access.
This could either simply be always enabled for all webstrates on the server or, at the very least, with the option to enable it for individual webstrates without having to edit the server config.

The usual authentication for the server naturally still applies, so it should mostly be an issue of adding the headers when an origin is presented in the request.

Example code could look something like this:
```
if (typeof req.headers['origin'] !== "undefined"){
        res.header("Access-Control-Allow-Origin", req.headers['origin']);
        res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
        res.header("Access-Control-Allow-Credentials", "true");
}
```

**Comment by svnhub** [comment]
The last commit only sets CORS headers on the webstrate and related requests itself, which works perfectly. However, the same allowed origins should probably also be allowed to access the assets connected with the webstrate?
In other words maybe the setCorsHeaders() call should be moved up a bit to include the asset handling?

**Comment by kbadk** [comment]
Yes, of, course, sorry about that!
