### ISSUE TITLE
Allow client-side configuration of isTransientElement

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#50]
Allow developers to change the `isTransientElement` function on client-side to create a custom configuration of what elements a client should consider transient and what elements it should send to the server.

Example of an alternative configuration:
```
isTransientElement: (DOMNode) => {
    return DOMNode.matches('transient,.transient,[transient]');
}
``` 

Two change requests:
1. Expose `isTransientElement` through an API on the root webstrate object. For example, add it to the `webstrate.config` object.
2. Introduce a new event in Webstrates that is triggered on the root webstrate object after the DOM has been populated and before any of the JavaScripts (scripts) get executed to give ample time to override the `isTransientElement` function.

In addition, it might make sense to expose the entire client `config.js` configuration on client-side to make a webstrate ultimately configurable.

**Comment by kbadk** [comment]
Implemented in bc59b7b4a2602e619ec0d06075ea4b5507653dd3.
