### ISSUE TITLE
User login and logout with a JavaScript API

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#55]
The login and logout of Webstrates currently works with `https://webstrates.cs.au.dk/auth/github` (login) and `https://webstrates.cs.au.dk/auth/logout` (logout). This, however, requires opening the URLs in a new window (or tab or popup window).

A JavaScript API allowing to login and logout would allow application developers to implement custom login/logout user interfaces, which are tied to the particular application and its UI look & feel.

In addition, opening a webstrate and then logging in using a new tab requires reloading the webstrate in order to receive the `webstrate.user` object with the logged in user data.

**Comment by kbadk** [comment]
Outside of simply opening popup windows with GitHub's login pace, this isn't possible. Websites aren't allowed to make POST requests on behalf of their users. This would be a huge vulnerability.

**Comment by raedle** [comment]
How do other frameworks such as Meteor do it then?

https://guide.meteor.com/accounts.html#oauth

**Comment by kbadk** [comment]
We also provide an API and it’s located at `/auth/github` as you said yourself. I haven’t used Meteor I’m guessing it’s the same way they do it.
