### ISSUE TITLE
Expose maxAssetSize to clients

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#59]
Having the maxAssetSize information on the client would help to pre-check file size before uploading. The server wouldn't get strained by the asset upload, which eventually would fail due to a too large file size.

Example:
```
if (file.size > webstrate.config.maxAssetSize) {
  alert('Can't handle this file. It's too large for me, sorry');
}
else {
  // upload asset
  webstrate.uploadAsset(() => {
    ...
  });
}
```

**Comment by kbadk** [comment]
Added in 8fa46bba03bda6da81c64c71ba674bb5bbe6aaff.
