### ISSUE TITLE
Throw an error when trying to tag a webstrate with a period

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#62]
Creating a tag that contains a period `.` is supported. Restoring tags with the API as well as the `?restore` query parameter works as expected. However, creating a copy of a tagged version where the label contains a period will result in `Asset "<TAG_LABEL>" not found.` (e.g., https://webstrates.cs.au.dk/tasty-rat-10/test.abc/?copy)

Throwing an error similar to tagging a webstrate with a leading `number` could prevent confusion.

**Comment by kbadk** [comment]
I think we could just allow periods using the same technique we're allowing periods in attribute names, even though keys with periods aren't supported in MongoDB.
