### ISSUE TITLE
Bug in createNewDocument()

### ISSUE THREAD

**Issue by parsoyaarihant** [Webstrates/Webstrates#72]
When a webstrate is copied to a new WebstrateID (using `?copy=<WebstrateId>`). And that webstrate already exist, then we expect to get `Error('Webstrate already exists.')`(https://github.com/Webstrates/Webstrates/blob/master/helpers/DocumentManager.js#L46)

However that can be prevented due to this condition:
https://github.com/Webstrates/Webstrates/blob/master/helpers/DocumentManager.js#L57

**Comment by kbadk** [comment]
Great catch, @parsoyaarihant. Thanks!
