### ISSUE TITLE
Continue when an error occurs during opening a 'webstrate archive'?

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#83]
Does it make sense to continue `importing` a webstrate archive after `yauzl` throws an error, or should the statement in L720 `return`?

https://github.com/Webstrates/Webstrates/blob/601dceb9fe75f566406661efa12d83d923fbf849/helpers/HttpRequestController.js#L720

**Comment by kbadk** [comment]
It should probably return yes. Good catch.
