### ISSUE TITLE
Installation in Windows

### ISSUE THREAD

**Issue by maski89** [Webstrates/Webstrates#87]
When attempting to install Webstrates under Windows 10, the manual of the website (https://webstrates.github.io/gettingstarted/installation.html) is not working. There seems to be two issues (at least for me):

1. The build script for Windows needs to be `SET NODE_ENV='production' & webpack -p` instead of `NODE_ENV='production' webpack -p`. Can you add specific scripts depending on the OS?

2. When building with the script above (`npm run build`) after using `npm install --production`, the following error occurs:

```
ERROR in Entry module not found: Error: Can't resolve 'eslint-loader' in 'e:\Projects\_Codestrates\Webstrates'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! Webstrates@1.6.0 build: `SET NODE_ENV='production' & webpack -p`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the Webstrates@1.6.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marcel\AppData\Roaming\npm-cache\_logs\2018-12-05T08_45_22_347Z-debug.log
```

When using the normal `npm install` building works fine. My node version is `v10.10.0` with npm `6.4.1`. If this problem is related to the node version, this second issue can be ignored.

**Comment by kbadk** [comment]
That sucks!

The instructions on the Installation page indeed doesn't work for Windows 10. According to the Disqus comment, on Windows, `package.json` needs to be changed to

```javascript
`"build": "SET NODE_ENV=production & webpack -p --config ./webpack.config.js" ,
```

(If the Disqus comments aren't showing up for you, you should probably disable your adblocker for the documentation).

1. Unfortunately, npm doesn't allow you to add specific scripts depending on OS. That would be neat, though.

2. Could you show me your debug log here? Or alternatively send it to me on Slack.

**Comment by kbadk** [comment]
It appears that Windows will see `SET NODE_ENV=production & webpack -p` and define `NODE_ENV` as `production ` (notice the space at the end).

We could solve this problem by writing: `SET NODE_ENV=production& webpack -p` instead, but to avoid issues in the future, I'll make sure we trim the `NODE_ENV` variable before checking whether it matches `production`.

Thank for the help in hunting this down, @maski89!

**Comment by StephProjet** [comment]
Hi, I have the same problem when i install webstrates on windows 10.
when i change the build path like that:
` "build": "SET NODE_ENV=production & webpack -p --config ./webpack.config.js",`

I have error when i type: 

`npm install --production`
`npm run build`

If anybody can help me?

![error](https://user-images.githubusercontent.com/37551153/81778813-850c5b80-94c1-11ea-95df-51d344938e0e.PNG)

![erro1](https://user-images.githubusercontent.com/37551153/81778941-b84eea80-94c1-11ea-8768-e364c164cf5c.PNG)
![erro3](https://user-images.githubusercontent.com/37551153/81779142-18459100-94c2-11ea-887e-ad67d3f1c26c.PNG)
